[package]
name = "hexchat_translator"
version = "0.1.0"
authors = ["ttappr <tmtappr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hexchat_translator"
crate-type = ["cdylib"]

[dependencies]
hexchat_api = { path = "../hexchat_api" }
#http = "0.2"
#reqwest = "0.11"
ureq = "0.9"
urlparse = "0.7"
