[package]
name = "hexchat_translator"
version = "0.1.0"
authors = ["ttappr <tmtappr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hexchat_translator"
crate-type = ["cdylib"]

[dependencies]
hexchat_api = { path = "../hexchat_api" }
#lazy_static = "1.4"
regex = "1"
serde_json = "1.0"
ureq = { version = "2.0" }
urlparse = "0.7"
